---
# tasks file for change_motd
- name: Change MOTD
  copy:
    content: " \n"
    dest: /etc/motd

- name: Disable Default MOTD
  file:
    dest: "/etc/update-motd.d/"
    mode: "u-x,g-x,o-x"
    state: directory
    recurse: yes
